[workspace]
resolver = "2"
members = [
    "crates/cli",
    "crates/transaction-processor",
    "crates/tests",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.95"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
anyhow = "1"
async-trait = "0.1"
clap = { version = "4", features = ["derive"] }
csv-async = { version = "1", features = ["tokio"] }
futures = "0.3"
num_cpus = "1"
rust_decimal = { version = "1.41", features = ["serde-str"] }
serde = { version = "1", features = ["derive"] }
thiserror = "1"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
